# Generated by Django 4.0.5 on 2022-06-20 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_category_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watched_by_users',
            field=models.ManyToManyField(blank=True, related_name='user_watched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
